// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

const schema = process.env["PRISMA_SCHEMA"] ?? "prisma/schema.prisma";
const isPostgresSchema = schema.startsWith("prisma-postgres/");

export default defineConfig({
  schema,
  migrations: {
    path: isPostgresSchema ? "prisma-postgres/migrations" : "prisma/migrations",
  },
  datasource: {
    url: process.env["DATABASE_URL"],
  },
});
